### PR TITLE
Made changes to header and added footer

### PR DESCRIPTION
**Pull request by riiyaaa**
- Added **Explore** and **Contact** on the header and linked them.

hello jobs 1

- Added a **footer** with contact icons

footer

- **Hover effect** on icons

hover

**RESPONSIVE**

_Tab View_

TAB FOOTER

_Mobile View_

mobile s

mobile l

### CODE REVIEW

**Comment by harshita2216** [comment]
I think you were assigned the header? @riiyaaa

**Comment by riiyaaa** [comment]
Yes, but the requirements stated 'link it to footer' . So I added a rough one.

**Comment by harshita2216** [comment]
> Yes, but the requirements stated 'link it to footer' . So I added a rough one.

Sorry about the confusion, but you were supposed to make a new header in accordance with the UI design shared with y'all on Discord. Please check point no. 4 of the issue assigned to you.

**Comment by riiyaaa** [comment]
Okay, should I discard that footer then?

**Comment by harshita2216** [comment]
> Okay, should I discard that footer then?

Yes and the header as well. You do have the design right?

**Comment by riiyaaa** [comment]
> https://www.figma.com/file/MQTSqQLlhYHLfT1DFZreQv/Untitled?node-id=0%3A1
> 
> Check out the header here! :) You may tweak it as per your choice.

Thankyou!

**Comment by lawanu-tech** [comment]
> > Yes, but the requirements stated 'link it to footer' . So I added a rough one.
> 
> Sorry about the confusion, but you were supposed to make a new header in accordance with the UI design shared with y'all on Discord. Please check point no. 4 of the issue assigned to you.

@harshita2216 Harshita , can I also join the Discord server or is it specific to a certain group of people?

**Comment by harshita2216** [comment]
> > > Yes, but the requirements stated 'link it to footer' . So I added a rough one.
> > 
> > 
> > Sorry about the confusion, but you were supposed to make a new header in accordance with the UI design shared with y'all on Discord. Please check point no. 4 of the issue assigned to you.
> 
> @harshita2216 Harshita , can I also join the Discord server or is it specific to a certain group of people?

If you're a JWOC participant, you may.

**Comment by riiyaaa** [comment]
Header

header1

Hover effects:

hover effect
hover effect1

**Comment by harshita2216** [comment]
Are you done with this? 
This looks incomplete to me. Can you please check the design? And also add responsiveness. 😊 @riiyaaa

**Comment by riiyaaa** [comment]
> Are you done with this? This looks incomplete to me. Can you please check the design? And also add responsiveness. 😊 @riiyaaa

okayy

**Pull request closed without merging**
